name: 'Publish Image'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:   

jobs:
  publish_container:
    runs-on: ubuntu-latest
    env: 
      CONTAINER_URL: kabeldd.azurecr.io
      IMAGE_NAME: quironlabeler
      RESOURCE_GROUP: RG_Playground
      WEBAPP_NAME: quironlabeler

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Login Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CREDENTIALS }}
      - name: 'Login CR'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.CONTAINER_URL }}
          username: ${{ secrets.USERNAME_CR }}
          password: ${{ secrets.KEY1_CR }}
      - run: |
          docker build . -t ${{ env.CONTAINER_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.CONTAINER_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      - name: Set Web App ACR authentication
        uses: Azure/appservice-settings@v1
        with:
          app-name: ${{ env.WEBAPP_NAME }} 
          app-settings-json: |
            [
                {
                    "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                    "value": "${{ secrets.KEY1_CR }}",
                    "slotSetting": false
                },
                {
                    "name": "DOCKER_REGISTRY_SERVER_URL",
                    "value": "https://${{ env.CONTAINER_REGISTRY }}",
                    "slotSetting": false
                },
                {
                    "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                    "value": "${{ secrets.USERNAME_CR  }}",
                   "slotSetting": false
                }
            ]
      - name: 'Deploy to Azure Web App for Container'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.WEBAPP_NAME }} 
          images: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          startup-command: 'npm start'   
