name: 'Publish Image'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:   

jobs:
  publish_container:
    runs-on: ubuntu-latest
    env: 
      CONTAINER_URL: kabeldd.azurecr.io
      IMAGE_NAME: quironlabeler
      RESOURCE_GROUP: RG_Playground

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Login Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CREDENTIALS }}
      - name: 'Login CR'
        uses: azure/docker-login@v1
        with:
          login-server: env.CONTAINER_URL
          username: ${{ secrets.CLIENT_ID  }}
          password: ${{ secrets.CLIENT_SECRET }}
      - run: |
          docker build . -t ${{ env.CONTAINER_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.CONTAINER_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      - name: Deploy to Azure Container Instances
        uses: Azure/aci-deploy@v1
        with:
          resource-group: env.RESOURCE_GROUP
          dns-name-label: ${{ env.CONTAINER_URL }}/${{ env.IMAGE_NAME }}
          image: ${{ env.CONTAINER_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          registry-username: ${{ secrets.CLIENT_ID }}
          registry-password: ${{ secrets.CLIENT_SECRET }}
          name: env.IMAGE_NAME
          location: 'west europe'        
